# Generated by Django 3.1.2 on 2020-10-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField(max_length=100)),
                ('skill2', models.CharField(max_length=100)),
                ('skill3', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
